"""
DailyBrief — LLM-generated daily intelligence report.
One record per calendar date.
"""
from __future__ import annotations

from typing import Optional

from sqlalchemy import Date, Float, Integer, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class DailyBrief(Base):
    __tablename__ = "daily_briefs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # One brief per date (UTC)
    date: Mapped[str] = mapped_column(String(10), nullable=False, unique=True, index=True)
    # stored as "YYYY-MM-DD" — plain string for SQLite compat, trivially
    # converted to date in PostgreSQL via CHECK constraint in migration.

    # ---- Content ------------------------------------------------------------
    headline: Mapped[str] = mapped_column(String(300), nullable=False)
    # e.g. "GPT-5 launch dominates AI news as EU regulation vote looms"

    summary: Mapped[str] = mapped_column(Text, nullable=False)
    # 3-5 paragraph narrative generated by LLM

    key_themes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # JSON: ["LLM release", "AI regulation", "Open Source surge"]

    top_story_ids: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # JSON: [42, 17, 88, 3, 9]  — ordered list of NewsArticle IDs

    trending_tag_ids: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # JSON: [1, 5, 12]

    trending_company_ids: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # JSON: [3, 7]

    # ---- Stats --------------------------------------------------------------
    total_articles_processed: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    total_articles_published: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    avg_importance_score: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)

    # ---- Generation metadata ------------------------------------------------
    llm_model_used: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    generation_duration_s: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    is_published: Mapped[bool] = mapped_column(
        "is_published", default=False, nullable=False, index=True
    )

    def __repr__(self) -> str:
        return f"<DailyBrief date={self.date!r} published={self.is_published}>"
