import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { getBrief, getArticle, REVALIDATE_MEDIUM } from '@/lib/api'
import { formatDate, SITE_NAME } from '@/lib/utils'
import { ArticleCard } from '@/components/news/ArticleCard'

export const revalidate = REVALIDATE_MEDIUM

interface Props {
  params: { date: string }
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  try {
    const brief = await getBrief(params.date)
    return {
      title: `Daily Brief ${formatDate(brief.date)} — ${brief.headline}`,
      description: brief.summary,
    }
  } catch {
    return { title: 'Daily Brief' }
  }
}

export default async function DailyBriefPage({ params }: Props) {
  let brief
  try {
    brief = await getBrief(params.date)
  } catch {
    notFound()
  }

  // Hydrate top stories
  const storyResults = await Promise.allSettled(
    brief.top_stories.map((s) => getArticle(s.slug))
  )
  const stories = storyResults
    .filter((r) => r.status === 'fulfilled')
    .map((r) => (r as PromiseFulfilledResult<any>).value)

  return (
    <div className="max-w-3xl mx-auto space-y-8">
      {/* Breadcrumb */}
      <nav className="flex items-center gap-2 text-xs text-gray-400">
        <Link href="/" className="hover:text-brand-600">Home</Link>
        <span>/</span>
        <Link href="/daily" className="hover:text-brand-600">Daily Brief</Link>
        <span>/</span>
        <span className="text-gray-600">{brief.date}</span>
      </nav>

      {/* Header */}
      <header className="card bg-gradient-to-br from-brand-600 to-brand-700 text-white border-0">
        <p className="text-xs font-semibold uppercase tracking-widest text-blue-200 mb-1">
          Daily Brief
        </p>
        <h1 className="text-2xl font-bold mb-2">{brief.headline}</h1>
        <p className="text-sm text-blue-100 leading-relaxed mb-4">{brief.summary}</p>

        {brief.key_themes.length > 0 && (
          <div className="flex flex-wrap gap-1.5">
            {brief.key_themes.map((theme, i) => (
              <span key={i} className="badge bg-white/15 text-blue-50 text-[10px]">
                {theme}
              </span>
            ))}
          </div>
        )}

        <div className="mt-4 pt-3 border-t border-white/20 flex items-center gap-4 text-xs text-blue-200">
          <span>{formatDate(brief.date)}</span>
          <span>·</span>
          <span>{brief.total_articles_published} articles published</span>
          {brief.llm_model_used && (
            <>
              <span>·</span>
              <span>Generated by {brief.llm_model_used}</span>
            </>
          )}
        </div>
      </header>

      {/* Trending tags from brief */}
      {brief.trending_tags.length > 0 && (
        <section>
          <p className="section-title">Trending Today</p>
          <div className="flex flex-wrap gap-1.5">
            {brief.trending_tags.map((tag) => (
              <Link
                key={tag.slug}
                href={`/topics/${tag.slug}`}
                className="badge badge-blue no-underline"
              >
                {tag.name}
                <span className="ml-1 text-blue-500">{tag.news_count_7d}↑</span>
              </Link>
            ))}
          </div>
        </section>
      )}

      {/* Top stories */}
      {stories.length > 0 && (
        <section>
          <p className="section-title">Top Stories</p>
          <div className="space-y-4">
            {stories.map((article, i) => (
              <div key={article.id} className="flex gap-3">
                <span className="text-2xl font-bold text-gray-100 w-8 flex-shrink-0 text-center leading-tight">
                  {i + 1}
                </span>
                <div className="flex-1">
                  <ArticleCard article={article} />
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {/* Structured data */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'NewsArticle',
            headline: brief.headline,
            description: brief.summary,
            datePublished: brief.date,
            publisher: { '@type': 'Organization', name: SITE_NAME },
          }),
        }}
      />
    </div>
  )
}
